name: Publish

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

env:
  APP_NAME: fyne_demo_

jobs:
  build:
    name: Publish binaries
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23.1
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          install: mingw-w64-x86_64-toolchain
      - name: Install Fyne CLI
        run: |
          go install fyne.io/fyne/v2/cmd/fyne@latest
      - name: Install project dependencies
        run: |
          go mod tidy
      - name: Build packages
        run: |
          fyne package --release --executable dist/demo.exe
      - name: Zip file
        run: |
          zip -r ${APP_NAME}Windows_x86_64.zip dist/      
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: ${{ env.APP_NAME }}*
          # asset_name: mything
          tag: ${{ github.ref }}
          overwrite: true
          body: "test fyne windows-3"